FROM frolvlad/alpine-python-machinelearning

ENV APP_DIR=/app/ml

WORKDIR $APP_DIR

#ADD everything from ml to $APP_DIR
ADD ml $APP_DIR

EXPOSE 4000

ENTRYPOINT python3 labelizer_server.py
#ENTRYPOINT python3 test_dico.py



