FROM node

ENV APP_DIR=/app/sonomood

WORKDIR $APP_DIR

RUN mkdir src

ADD src $APP_DIR/src
ADD package.json tsconfig.json yarn.lock $APP_DIR
RUN npm install
RUN yarn install

EXPOSE 3000

ENTRYPOINT yarn dev
